services:
  yarp.gateway:
    container_name: yarp.gateway
    build:
      context: .
      dockerfile: SwaggerWithOcelotAndYarp.Yarp.Gateway/Dockerfile
    image: yarp-gateway:latest
    ports:
    - 5000:8080    
    depends_on:
    - order.webapi
    - catalog.webapi
    networks:
    - my_network
  order.webapi:
    container_name: order-webapi
    build:
      context: .
      dockerfile: SwaggerWithOcelotAndYarp.Order/Dockerfile
    image: order-webapi:latest
    ports:
    - 5001:8080
    networks:
    - my_network
  catalog.webapi:
    container_name: catalog-webapi
    build:
     context: .
     dockerfile: SwaggerWithOcelotAndYarp.Catalog/Dockerfile
    image: catalog-webapi:latest
    ports:
    - 5002:8080  
    networks:
    - my_network

networks:
  my_network:
    driver: bridge