services:
  yarp.gateway:
    container_name: yarp.gateway
    build:
      context: .
      dockerfile: SwaggerWithOcelotAndYarp.Yarp.Gateway/Dockerfile
    image: yarp-gateway:latest
    ports:
    - 5000:8080
  order.webapi:
    container_name: order-webapi
    build:
      context: .
      dockerfile: SwaggerWithOcelotAndYarp.Order/Dockerfile
    image: order-webapi:latest
    ports:
    - 5001:8080
  catalog.webapi:
    container_name: catalog-webapi
    build:
     context: .
     dockerfile: SwaggerWithOcelotAndYarp.Catalog/Dockerfile
    image: catalog-webapi:latest
    ports:
    - 5002:8080  